on: [push, pull_request]

name: Build
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.22.x
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install package
        run: |
          sudo apt-get update -y; sudo apt-get install -y libmpv-dev
        if: runner.os == 'Linux'

      - name: Build
        run: go build ./...

      - name: Build ./examples
        run: go build -C examples
